on: push

name: Integration

jobs:
    build:  
        runs-on: macos-11
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-go@v3
              with: 
                go-version: '1.18'
            - name: Build
              env:
                CGO_ENABLED: 0
              run: |
                go build

            - name: Run Tests
              run: |
                go test
                

                
             
           
      